[project]
name = "poke-api-javier-barba"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.14"
dependencies = [
    "bcrypt>=5.0.0",
    "fastapi>=0.121.0",
    "httpx>=0.28.1",
    "passlib[argon2]>=1.7.4",
    "pydantic[email]>=2.12.4",
    "pyjwt>=2.10.1",
    "python-dotenv>=1.2.1",
    "python-jose>=3.5.0",
    "python-multipart>=0.0.20",
    "slowapi>=0.1.9",
    "sqlmodel>=0.0.27",
    "utils>=1.0.2",
    "uvicorn>=0.38.0",
]
